env = Environment(parse_flags='-g -O0 -Werror -Wall -lpthread')
env.Append(CPPPATH=['kernel_linux', 'lib', 'x86', '.'])

util = env.Clone()
unittest = env.Clone()
unittest.Append(CPPDEFINES='__USER_UNIT_TEST')

util.Program('kernel_linux/controller',
             ['kernel_linux/controller.cc',
              'kernel_linux/controller_stats_interface.cc',
              'kernel_linux/linux_device.cc'])
util.Program('kernel_linux/hypercall_host',
             ['kernel_linux/hypercall_host.cc',
              'kernel_linux/linux_device.cc'])

unittest.Program('kernel_linux/list_unittest.c')
unittest.Program('kernel_linux/page_table_unittest.c')
unittest.Program('barrier_unittest.c')
unittest.Program('utils_unittest.c')
unittest.Program('kernel_linux/clients/umbra/pagepool_unittest.c')
