name: ci-drk
on: [push, pull_request]
jobs:
  x86-64:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          submodules: true

      - name: Setup build environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt update
          sudo apt install -y doxygen vera++ libelf-dev scons cmake g++-multilib
          echo "MAKE_CMD=make -j$(nproc)" >> $GITHUB_ENV

      - name: Download and extract kernel source
        run: |
          VERSION="6.6.130"
          wget --quiet https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-$VERSION.tar.xz
          tar -xf linux-$VERSION.tar.xz
          echo "KERNEL_DIR=linux-$VERSION" >> $GITHUB_ENV

      - name: Generate kernel headers
        working-directory: ${{ env.KERNEL_DIR }}
        run: |
          make defconfig
          $MAKE_CMD modules_prepare

      - name: Generate DynamoRIO headers via CMake
        run: |
          mkdir -p build
          cd build
          cmake ..

      - name: Build drk
        # TODO i#10: Convert to cmake.
        run: cd core && $MAKE_CMD -f drk.mk KERNELDIR=$GITHUB_WORKSPACE/$KERNEL_DIR
